apiVersion: v1
kind: Pod
metadata:
  labels:
    app: devpod
  name: devpod-go
spec:
  containers:
    - name: devpod-g-container
      image: devpod-go:dev
      imagePullPolicy: Never
      volumeMounts:
        - mountPath: /go/src
          name: src
  volumes:
    - name: src
      hostPath:
        path: /path/to/src