apiVersion: v1
kind: Pod
metadata:
  labels:
    app: dev
  name: dev-go
spec:
  containers:
    - name: dev-go-container
      image: dev:go15
      imagePullPolicy: Never
      volumeMounts:
        - mountPath: /go/src
          name: src
      ports:
        - containerPort: 23456
      resources:
        requests:
          memory: "1024Mi"
          cpu: "1000m"
        limits:
          memory: "2048Mi"
          cpu: "2000m"
  volumes:
    - name: src
      hostPath:
        path: /path/to/src
# Use kubectl port-forward instead
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: dev-service
# spec:
#   type: NodePort
#   selector:
#     app: dev
#   ports:
#     - port: 23456
#       targetPort: 23456
#       nodePort: 32345