# this config file contains all config fields with comments
# NOTE: this is not a particularly useful config file
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
# patch the generated kubeadm config with some extra settings
# kubeadmConfigPatches:
# - |
#   apiVersion: kubelet.config.k8s.io/v1beta1
#   kind: KubeletConfiguration
#   evictionHard:
#     nodefs.available: "0%"
# patch it further using a JSON 6902 patch
# kubeadmConfigPatchesJSON6902:
# - group: kubeadm.k8s.io
#   version: v1beta2
#   kind: ClusterConfiguration
#   patch: |
#     - op: add
#       path: /apiServer/certSANs/-
#       value: my-hostname
# 1 control plane node and 3 workers
nodes:
- role: control-plane
  image: kindest/node:v1.19.7@sha256:a70639454e97a4b733f9d9b67e12c01f6b0297449d5b9cbbef87473458e26dca
  extraMounts:
    - hostPath: C:\Users\super\go\src
      containerPath: /path/to/src
  # extraPortMappings:
  #   - containerPort: 32345
  #     hostPort: 32345
  #     # optional: set the bind address on the host
  #     # 0.0.0.0 is the current default
  #     listenAddress: "0.0.0.0"
  #     # optional: set the protocol to one of TCP, UDP, SCTP.
  #     # TCP is the default
  #     protocol: TCP
- role: worker
  image: kindest/node:v1.19.7@sha256:a70639454e97a4b733f9d9b67e12c01f6b0297449d5b9cbbef87473458e26dca
  extraMounts:
    - hostPath: C:\Users\super\go\src
      containerPath: /path/to/src
- role: worker
  image: kindest/node:v1.19.7@sha256:a70639454e97a4b733f9d9b67e12c01f6b0297449d5b9cbbef87473458e26dca
  extraMounts:
    - hostPath: C:\Users\super\go\src
      containerPath: /path/to/src
